image: thunderdb/build

variables:
  REVIEWDOG_VERSION: 0.9.9
  REVIEWDOG_GITLAB_API_TOKEN: $REVIEWDOG_TOKEN
  CODECOV_TOKEN: $CODECOV_TOKEN

before_script:
  # Setup dependency management tool
#  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
#  - chmod +x $GOPATH/bin/dep
#  - go get github.com/mattn/goveralls
#  - go get github.com/haya14busa/goverage
#  - go get github.com/golang/lint/golint
#  - go get github.com/haya14busa/reviewdog/cmd/reviewdog
  - go get github.com/wadey/gocovmerge
  - mkdir -p $GOPATH/src/gitlab.com/
  - cp -r /builds/thunderdb $GOPATH/src/gitlab.com/
  - cd $GOPATH/src/gitlab.com/thunderdb/ThunderDB
#  - dep ensure
  - mkdir -p ~/bin/ && export PATH="~/bin/:$PATH"
#  - curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o ~/bin/reviewdog && chmod +x ~/bin/reviewdog

test-my-project:
  stage: test
  script:
    - bash build.sh
    - go test -v -race $(go list ./... | grep -v "/vendor/") -coverprofile cover.out
    - gocovmerge cover.out $(find cmd -name "*.cover.out") > coverage.txt
    - bash <(curl -s https://codecov.io/bash)
    - >-
      golint ./... | grep -v 'vendor/' | grep -v 'server/' | grep -v 'utils/' | reviewdog -f=golint -reporter=gitlab-mr-commit || true

