version: '3'

services:
  covenantsql_bp_0:
    image: covenantsql.io/covenantsql:latest
    container_name: covenantsql_bp_0
    restart: always
    environment:
      COVENANT_ROLE: blockproducer
      COVENANT_CONF: ./node_0/config.yaml
    volumes:
      - ./test/service/node_0/:/app/node_0/
    networks:
      default:
        ipv4_address: 172.254.1.2
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  covenantsql_bp_1:
    image: covenantsql.io/covenantsql:latest
    container_name: covenantsql_bp_1
    restart: always
    environment:
      COVENANT_ROLE: blockproducer
      COVENANT_CONF: ./node_1/config.yaml
    volumes:
      - ./test/service/node_1/:/app/node_1/
    networks:
      default:
        ipv4_address: 172.254.1.3
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  covenantsql_bp_2:
    image: covenantsql.io/covenantsql:latest
    container_name: covenantsql_bp_2
    restart: always
    environment:
      COVENANT_ROLE: blockproducer
      COVENANT_CONF: ./node_2/config.yaml
    volumes:
      - ./test/service/node_2/:/app/node_2/
    networks:
      default:
        ipv4_address: 172.254.1.4
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  covenantsql_miner_0:
    image: covenantsql.io/covenantsql:latest
    container_name: covenantsql_miner_0
    restart: always
    environment:
      COVENANT_ROLE: miner
      COVENANT_CONF: ./node_miner_0/config.yaml
    volumes:
      - ./test/service/node_miner_0/:/app/node_miner_0/
    networks:
      default:
        ipv4_address: 172.254.1.5
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  covenantsql_miner_1:
    image: covenantsql.io/covenantsql:latest
    container_name: covenantsql_miner_1
    restart: always
    environment:
      COVENANT_ROLE: miner
      COVENANT_CONF: ./node_miner_1/config.yaml
    volumes:
      - ./test/service/node_miner_1/:/app/node_miner_1/
    networks:
      default:
        ipv4_address: 172.254.1.6
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  covenantsql_miner_2:
    image: covenantsql.io/covenantsql:latest
    container_name: covenantsql_miner_2
    restart: always
    environment:
      COVENANT_ROLE: miner
      COVENANT_CONF: ./node_miner_2/config.yaml
    volumes:
      - ./test/service/node_miner_2/:/app/node_miner_2/
    networks:
      default:
        ipv4_address: 172.254.1.7
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  covenantsql_adapter:
    image: covenantsql.io/covenantsql_adapter:latest
    container_name: covenantsql_adapter
    restart: always
    ports:
      - "11105:4661"
    volumes:
      - ./test/service/node_c/config.yaml:/app/config.yaml
      - ./test/service/node_c/private.key:/app/private.key
      - ./test/service/node_c/:/app/node_c/
    networks:
      default:
        ipv4_address: 172.254.1.8

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.254.1.0/24
